### ISSUE TITLE
Max width or max height for images

### ISSUE THREAD

**Issue by Alex360hd** [toughdeveloper/oc-imageresizer-plugin#19]
Hello,

I need to resize image that way :

* It should never have a weight more than 180
* It should never have a height more than 100
* Is should keep aspect ratio and not crop

I tested all provided modes but can't find a way to do that. I exclude "exact" and "crop" mode because of the third point, so there is "auto", "portrait" and "landscape"

The problem with landscape/portrait mode is that they resize picture just by looking the width/height value. So I can have picture of 2000x100px or 180x2000px.

I don't find any mode that can do what I need, could you please point me the right direction if a solution actually exist ?

here is my code :

    image.jpg|media|resize(180, 100, { mode: '???' })

**Comment by toughdeveloper** [comment]
Hey, 

I would possibly use CSS to solve this, something along the lines of: 

```css
.image {
    height: 100px;
    width: 180px;
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
}
```

```html
<div class="image" style="background-image: url('{{ 'image.jpg' | media | resize(180, false, { mode: 'auto' }) }}');"></div>
```
